# Generated by Django 3.1.3 on 2021-01-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        ('notifications', '0002_auto_20210105_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='friends.invite', verbose_name='Инвайт')),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notification',),
        ),
    ]
